Update scripts

diff --git a/docker/build-eb-artifact b/docker/build-eb-artifact
--- a/docker/build-eb-artifact
+++ b/docker/build-eb-artifact
@@ -1,8 +1,28 @@
 #!/bin/bash
 
+if [ -z "$TARGET_ENV" ]
+then
+    echo Source environment variables using
+    echo "    \$ source docker/env/<your target environment>"
+    exit 2
+fi
+
+# Create git archive
 rm -f clubbable-eb.zip
 git archive --format=zip HEAD > clubbable-eb.zip
-src/clubbable/manage.py collectstatic --noinput --settings clubbable.settings.production
+
+# Render templates
+cat docker/templates/clubbable.conf | docker/render-env.py > docker/nginx/conf.d/clubbable.conf
+cat docker/templates/Dockerrun.aws.json | docker/render-env.py > Dockerrun.aws.json
+
+# Collect files
+src/clubbable/manage.py collectstatic --noinput --settings clubbable.settings.$TARGET_ENV
+cp src/submodules/docker-nginx-certbot/src/nginx_conf.d/*.conf docker/nginx/conf.d/
 zip -r clubbable-eb.zip src/clubbable/clubbable/static
-zip -r clubbable-eb.zip src/clubbable/clubbable/settings
+zip clubbable-eb.zip src/clubbable/clubbable/settings/*.py
+zip clubbable-eb.zip docker/nginx/conf.d/*.conf
+zip clubbable-eb.zip docker/nginx/secrets/*
 zip clubbable-eb.zip Dockerrun.aws.json
+
+# Clean up
+rm docker/nginx/conf.d/*.conf
